finos/tracdap

- gradle/config.gradle
- gradle/functions.gradle
- gradle/plugins.gradle
- settings.gradle
- trac-libs/sql-drivers/build.gradle
- trac-plugins/aws-config/build.gradle
- trac-plugins/aws-config/src/main/java/com/accenture/trac/plugins/config/aws/AwsConfigLoader.java
- trac-plugins/aws-config/src/main/java/com/accenture/trac/plugins/config/aws/AwsConfigPlugin.java
- trac-plugins/aws-config/src/main/resources/META-INF/services/com.accenture.trac.common.config.IConfigPlugin
- trac-plugins/aws-config/src/main/resources/log4j2.xml
- trac-plugins/aws-config/src/test/java/com/accenture/trac/plugins/config/aws/AwsConfigLoaderTest.java
- trac-plugins/aws-config/src/test/resources/log4j2-test.xml
- trac-services/trac-gateway/build.gradle
- trac-services/trac-svc-meta/build.gradle
Created a plugin and loading mechanism for configs stored in AWS S3. Authentication relies on AWS credentials in the environment. Integration test requires credentials to be set up.
> Create a plugin for loading configs from AWS S3

- trac-api/trac-metadata/src/main/proto/trac/metadata/flow.proto
Add a search expression to each node in a flow
> Feature / Flow node search expressions

- trac-libs/trac-lib-test/src/test/java/com/accenture/trac/test/e2e/RunModelTest.java
- trac-runtime/python/src/trac/rt/impl/storage.py
Fix handling of output formats discovered during testing
> Fix / Result storage path

- .github/workflows/packaging.yml
- dev/compliance/owasp-false-positives.xml
- End-to-end Maven publish workflow was confirmed by release 0.4.3
> Automate final release step for Maven publishing

- tracdap-runtime/python/src/tracdap/rt/exec/context.py
- tracdap-runtime/python/src/tracdap/rt/impl/api_hook.py
Add the ApiGuard explicit call signature validation to API calls in the implementation of TracContext. Previously this guard was only applied to static API functions.
> Feature / API call signature validation for TracContext

- tracdap-libs/tracdap-lib-test/src/main/resources/sample_data/csv_basic_uk_dates.csv
- tracdap-runtime/python/src/tracdap/rt/_exec/context.py
- tracdap-runtime/python/src/tracdap/rt/_impl/data.py
- tracdap-runtime/python/src/tracdap/rt/_impl/storage.py
- tracdap-runtime/python/src/tracdap/rt/api/model_api.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_storage.py
- Allow specifying date format in storageProps for CSV codec
- Option to request dates as objects in Pandas dataframes
> Feature / Runtime date format options

- dev/docker/.dockerignore
- dev/docker/.gitignore
- dev/docker/README.md
- dev/docker/auth-tool.Dockerfile
- dev/docker/deploy-metadb.Dockerfile
- dev/docker/docker-compose.yaml
- dev/docker/tracdap-gateway.Dockerfile
- dev/docker/tracdap-svc-data.Dockerfile
- dev/docker/tracdap-svc-meta.Dockerfile
- dev/docker/tracdap-svc-orch-local.Dockerfile
- dev/docker/tracdap-svc-orch.Dockerfile
- dist/scripts/service-ctrl.bat
- dist/scripts/service-ctrl.sh
- gradle/versions.gradle
Add a dockerfile for each service to `dev/docker`.
Add `docker-compose.yaml`.
Describe usage in `dev/docker/README.md`.
> Feature / Add dockerfiles and docker-compose

- .github/workflows/build.yml
- .github/workflows/integration.yml
- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/job.proto
- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/model.proto
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/metadata/MetadataConstants.java
- tracdap-runtime/python/requirements.txt
- tracdap-runtime/python/setup.cfg
- tracdap-runtime/python/src/tracdap/rt/_exec/functions.py
- tracdap-runtime/python/src/tracdap/rt/_impl/repos.py
- tracdap-runtime/python/src/tracdap/rt/_impl/util.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_repos.py
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/IJobLogic.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/ImportModelJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunFlowJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunModelJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobLifecycle.java
Includes better handling of repo auth config
Includes testing for Git and PyPI repos
> Feature / Multiple packages per model repo

- doc/deployment/storage.rst
- tracdap-plugins/aws-storage/src/main/java/org/finos/tracdap/plugins/aws/storage/S3ObjectStorage.java
- tracdap-plugins/aws-storage/src/test/java/org/finos/tracdap/plugins/aws/storage/S3StorageOperationsTest.java
- tracdap-plugins/aws-storage/src/test/java/org/finos/tracdap/plugins/aws/storage/S3StorageReadWriteTest.java
- tracdap-runtime/python/src/tracdap/rt/_plugins/aws_storage.py
Support multiple credentials mechanisms for S3 storage (platform + runtime)
> Feature / AWS alternate credentials mechanism

- dev/compliance/owasp-false-positives.xml
- dist/scripts/service-ctrl.bat
- dist/scripts/service-ctrl.sh
- dist/template/etc/env.bat
- dist/template/etc/env.sh
- doc/deployment/authentication.rst
- doc/deployment/sandbox.rst
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/config/ConfigKeys.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/startup/StandardArgsProcessor.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/startup/Startup.java
- tracdap-libs/tracdap-lib-common/src/test/java/org/finos/tracdap/common/startup/StandardArgsProcessorTest.java
`SECRET_KEY` env variable was processed in startup scripts.
Now it is processed in Java, class `StandardArgsProcessor`.
`SECRET_KEY` env variable was renamed to `TRAC_SECRET_KEY`.
> Feature / Process SECRET_KEY env variable in Java

- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/MetadataApiImpl.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/services/MetadataWriteService.java
Remove non-batch operations from `MetadataWriteService`.
> Feature / Remove non-batch operations from MetadataWriteService

- dev/config/trac-devlocal-gateway.yaml
- dist/template/etc/trac-gateway.yaml
- tracdap-api/tracdap-config/src/main/proto/tracdap/config/common.proto
- tracdap-api/tracdap-config/src/main/proto/tracdap/config/gateway.proto
- tracdap-api/tracdap-config/src/main/proto/tracdap/config/platform.proto
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/auth/AuthInterceptor.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/auth/GrpcClientAuth.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/auth/JwtProcessor.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/auth/JwtValidator.java
- tracdap-libs/tracdap-lib-common/src/test/java/org/finos/tracdap/common/auth/JwtProcessorTest.java
- tracdap-libs/tracdap-lib-test/src/main/java/org/finos/tracdap/test/helpers/PlatformTest.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/TracPlatformGateway.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/proxy/rest/RestApiProxy.java
- tracdap-services/tracdap-gateway/src/test/resources/trac-unit-gateway-http1.yaml
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/TracDataService.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/service/DataService.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/service/FileService.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/TracMetadataService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/TracOrchestratorService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobLifecycle.java
Allow authentication and/or token signing to be disabled for testing in non-production environments
> Feature / Auth config

- tracdap-plugins/aws-storage/src/main/java/org/finos/tracdap/plugins/aws/storage/S3ObjectStorage.java
- tracdap-runtime/python/src/tracdap/rt/_plugins/aws_storage.py
Required to support S3 protocol on NetApp
> Feature / S3 storage custom endpoints

- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/config/rest/MetaApiRestMapping.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/routing/CoreRouter.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/routing/CoreRouterLink.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/routing/Http1Router.java
- tracdap-tools/secret-tool/src/main/java/org/finos/tracdap/tools/secrets/SecretTool.java
Separate core parts from HTTP/1 implementation
> Feature / Generalize proxy routing

- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/search.proto
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/SearchValidator.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/jdbc/JdbcSearchQueryBuilder.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/api/MetadataSearchApiTest.java
> Bugfix / Make SearchExpression optional in SearchParameters

- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/grpc/GrpcServerWrap.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/grpc/LoggingServerInterceptor.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/TracDataService.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/api/TracDataApi.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/TracMetadataService.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/TracMetadataApi.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/TrustedMetadataApi.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/TracOrchestratorService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/api/TracOrchestratorApi.java
Move logging logic to LoggingServerInterceptor.java
> Remove method descriptor from GrpcServerWrap

- examples/apps/javascript/run_examples.js
- examples/apps/javascript/src/streaming.js
- tracdap-api/packages/web/wrapper.js
Convert between Web API readable stream (browser streaming API) and event emitters (used in protobuf.js)
> Feature / Web api stream emitters

- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/grpc/ErrorMappingInterceptor.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/grpc/GrpcErrorMapping.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/grpc/GrpcServerWrap.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/TracDataService.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/TracMetadataService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/TracOrchestratorService.java
> Add ErrorMappingInterceptor

- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/flow.proto
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunFlowJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunModelJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunModelOrFlow.java
- tracdap-services/tracdap-svc-orch/src/test/java/org/finos/tracdap/svc/orch/jobs/RunFlowTest.java
> Add nodeAttrs to FlowNode

- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/TracDataService.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/TracMetadataService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/TracOrchestratorService.java
> Fix ordering of gRPC interceptors

- gradle/base-java.gradle
> Gradle settings correction - character encoding.

- examples/models/python/src/tutorial/model_1.py
- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/model.proto
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/ModelValidator.java
- tracdap-runtime/python/src/tracdap/rt/_impl/static_api.py
- tracdap-runtime/python/src/tracdap/rt/_impl/validation.py
- tracdap-runtime/python/src/tracdap/rt/api/hook.py
- tracdap-runtime/python/src/tracdap/rt/api/static_api.py
...plus small bug fix in tracdap-runtime/python/src/tracdap/rt/_impl/validation.py
> "label" field in ModelInputSchema and ModelOutputSchema

- tracdap-api/tracdap-services/src/main/proto/tracdap/api/data.proto
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/codec/arrow/ArrowDecoder.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/codec/arrow/ArrowEncoder.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/codec/csv/CsvDecoder.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/codec/csv/CsvEncoder.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/codec/json/JsonDecoder.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/codec/json/JsonEncoder.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/data/DataPipeline.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/data/pipeline/RangeSelector.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/storage/IDataStorage.java
- tracdap-libs/tracdap-lib-data/src/main/java/org/finos/tracdap/common/storage/flat/FlatDataStorage.java
- tracdap-libs/tracdap-lib-test/src/main/java/org/finos/tracdap/test/data/SingleBatchDataSink.java
- tracdap-libs/tracdap-lib-test/src/main/java/org/finos/tracdap/test/data/SingleBatchDataSource.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/service/DataService.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/service/RequestState.java
- tracdap-services/tracdap-svc-data/src/test/java/org/finos/tracdap/svc/data/api/DataOperationsTest.java
Include offset and limit as optional parameters in data read request
> Feature / Range API for data download

- tracdap-runtime/python/src/tracdap/rt/_impl/data.py
> Fix / Handle data conformance for column containing all null values

- .github/workflows/integration-cloud.yaml
See https://github.com/Azure/login/issues/403
> Fix / Breaking change in CI action for Azure login

- examples/models/python/config/optional_io.yaml
- examples/models/python/config/optional_io_2.yaml
- examples/models/python/data/inputs/account_filter.csv
- examples/models/python/src/tutorial/optional_io.py
- examples/models/python/src/tutorial/schemas/account_filter.csv
- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/model.proto
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/graph/GraphBuilder.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/metadata/MetadataBundle.java
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/consistency/JobConsistencyValidator.java
- tracdap-runtime/python/src/tracdap/rt/_exec/context.py
- tracdap-runtime/python/src/tracdap/rt/_exec/dev_mode.py
- tracdap-runtime/python/src/tracdap/rt/_exec/functions.py
- tracdap-runtime/python/src/tracdap/rt/_exec/graph.py
- tracdap-runtime/python/src/tracdap/rt/_exec/graph_builder.py
- tracdap-runtime/python/src/tracdap/rt/_impl/data.py
- tracdap-runtime/python/src/tracdap/rt/_impl/guard_rails.py
- tracdap-runtime/python/src/tracdap/rt/_impl/models.py
- tracdap-runtime/python/src/tracdap/rt/_impl/static_api.py
- tracdap-runtime/python/src/tracdap/rt/api/hook.py
- tracdap-runtime/python/src/tracdap/rt/api/model_api.py
- tracdap-runtime/python/src/tracdap/rt/api/static_api.py
- tracdap-runtime/python/test/tracdap_examples/test_tutorial.py
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/IJobLogic.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/ImportModelJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunFlowJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunModelJob.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/jobs/RunModelOrFlow.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobProcessorHelpers.java
- tracdap-services/tracdap-svc-orch/src/test/java/org/finos/tracdap/svc/orch/jobs/RunModelTest.java
Supported for models and flows, optional outputs in a flow can be passed as optional inputs to the next model
> Feature / Optional model inputs and outputs

- tracdap-api/packages/web/api_builder.js
- tracdap-api/packages/web/package-lock.json
- tracdap-api/packages/web/package.json
Start using new null semantics from Protobuf.js in the web bindings
https://github.com/protobufjs/protobuf.js/pull/2011
> Feature / Web bindings update

- dev/requirements.txt
- gradle/base-java.gradle
- gradle/versions.gradle
- tracdap-api/packages/web/package-lock.json
- tracdap-api/packages/web/package.json
- tracdap-runtime/python/requirements.txt
- tracdap-runtime/python/setup.cfg
Bump versions of core dependencies
> Compliance update

- dev/config/trac-devlocal.yaml
- dist/template/etc/trac-platform.yaml
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/netty/NettyHelpers.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/netty/ThreadPoolRejectionHandler.java
- tracdap-libs/tracdap-lib-test/src/main/resources/config/trac-e2e.yaml
- tracdap-libs/tracdap-lib-test/src/main/resources/config/trac-unit.yaml
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/proxy/grpc/GrpcWebProxy.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/proxy/http/Http1Proxy.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/proxy/http/Http1to2Proxy.java
* Fix memory leaks for corner cases in HTTP 1 -> 2 protocol converting proxy
* Improve logging for gRPC rejected execution of requests in thread pool (blocking) executor
* Increase task queue size for default setup of thread pool (blocking) executor
> Fix / Corner case memory and scheduling issues

- tracdap-services/tracdap-gateway/src/test/java/org/finos/tracdap/gateway/proxy/http/Http1ProxyTest.java
- tracdap-services/tracdap-gateway/src/test/java/org/finos/tracdap/gateway/test/Http1TestServer.java
- tracdap-services/tracdap-gateway/src/test/resources/trac-unit-gateway-http1.yaml
Use the JDK HttpServer in com.sun.net as the test server for HTTP proxy testing
> Improve gateway testing for HTTP proxy

- examples/models/python/config/quick_start.yaml
- examples/models/python/src/tutorial/quick_start.py
- tracdap-runtime/python/test/tracdap_examples/test_tutorial.py
Add a quick start model to the modelling examples
> Quick start example

- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/TracOrchestratorService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobProcessor.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobProcessorHelpers.java
Preview for RC 2, config objects will supersede this mechanism
> Decode runtime secrets from repo config

- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/plugin/ITracExtension.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/plugin/PluginRegistry.java
- tracdap-libs/tracdap-lib-orch/src/main/java/org/finos/tracdap/common/exec/BatchConfig.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/TracOrchestratorService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/api/MessageProcessor.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/api/TracOrchestratorApi.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/IJobExecutor.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobExecutor.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobExecutorState.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobManager.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobProcessor.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/service/JobProcessorHelpers.java
Orch service only in this PR, others  to follow
> Feature / Plugin registry for service setup

- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/data.proto
Struct fields are held in SchemaDefinition -> fields
> Remove unused metadata constructs

- .github/scripts/int-storage-azure-setup.sh
- .github/scripts/int-storage-gcs-setup.sh
- .github/workflows/integration.yml
- dev/ide/idea/runConfigurations/Runtime__PY___Integration__Azure_.xml
- tracdap-runtime/python/src/tracdap/rt/_impl/core/storage.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/storage_azure.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/int_storage_azure.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/int_storage_gcp.py
Exposes the Arrow native storage implementation for Azure
> Azure arrow native storage

- .github/workflows/integration.yml
- tracdap-api/packages/web/package-lock.json
- tracdap-runtime/python/src/tracdap/rt/_plugins/storage_azure.py
Backport dependabot update to release/0.9 branch
> Dependabot/npm and yarn/tracdap api/packages/web/tmp 0.2.5
