finos/tracdap

- trac-api/packages/javascript/README.md
This adds a real life example React App to the README.md that runs a valid dummy search using rpc. There are a few issues with this carried over from the previous version.
> Updated docs for rpc example locally

- gradle/functions.gradle
Problem manifests with macOS + IntelliJ IDEA 2021.1
Gradle not guaranteed to use rootDir for call to version script, so we set it explicitly
> Fix Gradle function calling git version script

- trac-runtime/python/src/trac/rt/impl/config_parser.py
- trac-runtime/python/src/trac/rt/impl/storage.py
- trac-runtime/python/test/trac_test/rt/impl/__init__.py
- trac-runtime/python/test/trac_test/rt/impl/test_config_parser.py
Add some basic checks around loading and applying runtime config, to catch common errors.
This is not an exhaustive validation, which is needed to close config validation gaps. However it should help provide useful messages in some off the most common error cases.
> Feature / Basic config validation

- .github/workflows/build.yml
- .github/workflows/compliance.yml
- README.md
- trac-runtime/python/README.md
- trac-runtime/python/setup.cfg
Update supported versions of Python and PySpark (test against Python 3.10 / PySpark 3.2)
Update READMEs for 0.3 release
> Prepare 0.3 release

- gradle/base-java.gradle
- gradle/versions.gradle
Stops the IDE from suggesting Java 17 language features!
> Set Java compatibility level at Java 11

- examples/rest_calls/create_flow.json
- trac-api/trac-metadata/src/main/proto/trac/metadata/flow.proto
- trac-libs/trac-lib-test/src/main/java/com/accenture/trac/test/meta/TestData.java
- trac-services/trac-svc-meta/src/test/java/com/accenture/trac/svc/meta/api/MetadataWriteApiTest.java
Use "from" and "to" for flow edges
Instead of "head" and "tail", which are less obvious and could cause confusion
> Fix / Simplify naming of flow edges

- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/services/MetadataWriteService.java
Make handling of controlled attrs in metadata service backwards compatible for 0.4.x releases
> Fix / Backwards compatibility for create/update attrs

- gradle/versions.gradle
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/proxy/http/Http1Proxy.java
- tracdap-services/tracdap-gateway/src/test/resources/trac-unit-gateway-http1.yaml
Handle trailing slashes in source / target paths for HTTP 1 proxy translation in the gateway
- Avoids adding a double slash, or removing a slash, in the translated path
> Fix / Gateway path translation

- tracdap-runtime/python/src/tracdap/rt/_exec/context.py
- tracdap-runtime/python/src/tracdap/rt/_impl/data.py
- tracdap-runtime/python/src/tracdap/rt/api/model_api.py
Setting this flag when calling get_pandas_table will encode temporal fields as Python objects instead of using NumPy datetime64 type
> Feature / Temporal objects flag in model runtime

- dist/scripts/service-ctrl.sh
- dist/template/etc/trac-gateway-example.yaml
- dist/template/etc/trac-logging-example.xml
- dist/template/etc/trac-platform-example.yaml
- etc/trac-logging.xml
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/startup/StandardArgsProcessor.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/startup/StartupSequence.java
- tracdap-libs/tracdap-lib-common/src/main/resources/log4j2.xml
Various fixes to the logging system
Default logging options handled correctly
System properties available for logging config
Rolling file loggers are now the default in the platform packages
Startup logger always logs to console, until the logging config is processed
> Fix / Default logging config

- tracdap-runtime/python/src/tracdap/rt/_exec/dev_mode.py
Allow an input to be used multiple times when auto-wiring a flow in dev mode, so long as all the models expect the same schema
> Feature / Flow auto-wiring update

- tracdap-runtime/python/src/tracdap/rt/_exec/context.py
- tracdap-runtime/python/src/tracdap/rt/_exec/functions.py
- tracdap-runtime/python/src/tracdap/rt/_impl/data.py
- tracdap-runtime/python/test/tracdap_test/rt/exec/test_context.py
Always perform data conformance using model schemas for model inputs and outputs
Previously conformance was only applied to job inputs / outputs, where case and column ordering can be different
> Fix / Use model schemas for data conformance

- dist/scripts/service-ctrl.sh
Make `service-ctrl.sh` POSIX compatible. The behavior of the script should be the same.
Changes in `service-ctrl.sh`:
* Replace `exit -1` with `exit 255`
* Replace == with = in `if` comparisons
* Replace bash variable substring with `case` statement
> Make service-ctrl.sh POSIX compatible

- tracdap-services/tracdap-svc-meta/src/schema/h2/rollout/001__trac_metadata.ddl
- tracdap-services/tracdap-svc-meta/src/schema/mariadb/rollout/001__trac_metadata.ddl
- tracdap-services/tracdap-svc-meta/src/schema/mysql/rollout/001__trac_metadata.ddl
- tracdap-services/tracdap-svc-meta/src/schema/postgresql/rollout/001__trac_metadata.ddl
- tracdap-services/tracdap-svc-meta/src/schema/sqlserver/rollout/001__trac_metadata.ddl
Flyway requires that v001 scripts are not altered (file checksum) from the previous version before applying v002
> Fix / Metadata in-place upgrade from 0.4 series

- dist/scripts/service-ctrl.bat
- dist/scripts/service-ctrl.sh
- dist/template/etc/env.bat
- dist/template/etc/env.sh
Fixes #201 
Support `SECRET_KEY` env variable in start scripts
> Fix / SECRET_KEY from environment in the start scripts

- tracdap-libs/tracdap-lib-test/src/main/java/org/finos/tracdap/test/helpers/PlatformTest.java
Fixes error in local integration tests on Windows:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/Users/...
```
> Bugfix / Path configuration in PlatformTest

- tracdap-api/tracdap-services/src/main/proto/tracdap/api/metadata_trusted.proto
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/api/MetadataApiValidator.java
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/api/MetadataTrustedApiValidator.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/MetadataApiImpl.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/TrustedMetadataApi.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/services/MetadataWriteService.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/api/MetadataWriteApiTest.java
Add preallocate batch operations to metadata (trusted API).
Operations:
* `preallocateIdBatch`
* `createPreallocatedObjectBatch`
> Feature / Batch preallocate operations for metadata

- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/IMetadataDal.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/jdbc/JdbcMetadataDal.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/services/MetadataWriteService.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/dal/MetadataDalEncodingTest.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/dal/MetadataDalReadTest.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/dal/MetadataDalSearchTest.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/dal/MetadataDalWriteTest.java
Remove from `IMetadataDal`:
* `saveNewTag`
* `saveNewVersion`
* `saveNewObject`
They are replaced with calls to batch versions (like `saveNewTags`).
> Feature / Remove non-batch methods from IMetadataDal

- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/IMetadataDal.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/jdbc/JdbcMetadataDal.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/services/MetadataWriteService.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/dal/MetadataDalWriteTest.java
Remove from `IMetadataDal`:
* `savePreallocatedObject`
* `preallocateObjectId`
Refactor `MetadataWriteService`.
> Feature / Remove non-batch preallocate methods from IMetadataDal

- examples/apps/javascript/package-lock.json
- examples/apps/javascript/package.json
- examples/apps/javascript/run_examples.js
- tracdap-api/packages/web/wrapper.js
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/ProtocolNegotiator.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/proxy/grpc/WebSocketsTranslator.java
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/routing/WebSocketsRouter.java
Various small fixes, enchantments and simplifications in the web API transport classes, primarily for web sockets although some are shared.
Two transports are available, "google" and "trac", available as options in the setup method. "google" supports unary and server streaming calls, "trac" also supports client streaming. The "google" transport is preferred unless client streaming is required.
A future PR will add an "optimal" transport, which wraps the existing two and automatically selects "trac" for client streaming uploads.
> Feature / Web API transport enhancements

- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/SchemaValidator.java
Continue to allow integer categorical fields until the 0.6 release
> Fix / integer categorical fields

- dev/ide/idea/runConfigurations/Tools__Deploy_Meta_DB.xml
A cosmetic change, which was needed to fix an error occurring when running "Deploy Meta DB" RunConfiguration in IntelliJ.
> Run configuration correction - Deploy Meta DB.

- tracdap-runtime/python/src/tracdap/rt/_exec/functions.py
- tracdap-runtime/python/src/tracdap/rt/_exec/runtime.py
- tracdap-runtime/python/src/tracdap/rt/_impl/guard_rails.py
- tracdap-runtime/python/src/tracdap/rt/_impl/shim.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_guard_rails.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_shim_loader.py
- tracdap-services/tracdap-gateway/src/main/java/org/finos/tracdap/gateway/ProtocolNegotiator.java
Prevent calling exec(), eval(), sys.exit() and other dangerous functions from model code
> Feature / Runtime guardrails

- dev/config/trac-logging.xml
- dist/template/etc/trac-logging.xml
RollingFile has been configured to change current log file once every defined time interval. Rolled log files are also deleted on regular basis - when they get old enough. In addition the log files are not deleted on service restart (thanks to append="true" option for the appender). 
There are 2 optional configuration files:
- for testing and development purposes with 2 minute long rolling time interval and 5 minute threshold for old files deletion
- for distribution purposes with 1 day long rolling time interval and 30 days threshold for old files deletion
Additional comment:
It was not necessary to modify the code. During the problem analysis there was some confusion about reading of the log4j configuration files - it came from the fact, that I was analyzing the configuration obtained …
> Logging configuration correction - RollingFile appender configured.

- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/SchemaValidator.java
This is a solution to  the issue [#290](https://github.com/finos/tracdap/issues/290).
> Do not allow integer categorical fields in the 0.6 release

- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/object_id.proto
- tracdap-libs/tracdap-lib-test/src/main/java/org/finos/tracdap/test/meta/TestData.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/jdbc/JdbcBaseDal.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/jdbc/JdbcMetadataDal.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/jdbc/JdbcReadBatchImpl.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/dal/jdbc/JdbcReadImpl.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/services/MetadataWriteService.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/api/MetadataReadApiTest.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/api/MetadataSearchApiTest.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/api/MetadataWriteApiTest.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/dal/MetadataDalReadTest.java
- tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/dal/MetadataDalSearchTest.java
* WIP
* WIP
* WIP
* WIP
* New test for isLatestTag and isLatestObject flags.
* WIP
* Old test correction.
* Tests modification: setting expected isLatest(...) flags instead of checking them with assertTrue or assertFalse.
* Cosmetic changes for issue 345.
> Backport / isLatestObject and isLatestTag flags in object_id (issue 345) (#349)

- gradle/versions.gradle
- tracdap-runtime/python/src/tracdap/rt/_impl/static_api.py
- tracdap-runtime/python/src/tracdap/rt/api/static_api.py
- tracdap-runtime/python/test/tracdap_test/rt/exec/test_context.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_models.py
* Apply type coercion where possible for default model parameters
* If type coercion is not possible, raise errors in the runtime rather than waiting for platform validation
> Fix / Type coercion for default model parameters

- tracdap-runtime/python/requirements_plugins.txt
- tracdap-runtime/python/setup.cfg
- tracdap-runtime/python/src/tracdap/rt/_impl/storage.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/storage_aws.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/storage_azure.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/storage_gcp.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/storage_local.py
- tracdap-runtime/python/src/tracdap/rt/ext/storage.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_storage_local.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/int_storage_aws.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/int_storage_azure.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/int_storage_gcp.py
- tracdap-runtime/python/test/tracdap_test/rt/suites/file_storage_suite.py
The Arrow native FS implementation for GCS is not available on Windows, at least for some Windows versions. This PR adds an alternate implementation for GCS using the fsspec implementation and Arrow's fsspec wrapper.
Additionally, all the storage backends now support the "runtimeFs" property, which selects the storage implementation that is used in the runtime. The default is "auto", which selects the best available implementation for the current platform.
> Feature / Add fsspec implementation for GCP storage in the runtime

- .github/workflows/build.yml
- README.md
- dev/compliance/owasp-false-positives.xml
- gradle/versions.gradle
- tracdap-runtime/python/README.md
- tracdap-runtime/python/requirements.txt
- tracdap-runtime/python/setup.cfg
This allows moving on the Netty version, which is also a compliance point
> Feature / Update to Apache Arrow 13

- build.gradle
- dev/compliance/owasp-false-positives.xml
- dev/compliance/permitted-licenses.json
- dev/requirements.txt
- gradle/base-java.gradle
- gradle/versions.gradle
- settings.gradle
Includes Netty version update to 4.1.100 to address the HTTP/2 RST security issue
> Compliance update

- .github/workflows/build.yml
- gradle/versions.gradle
- tracdap-runtime/python/README.md
- tracdap-runtime/python/requirements.txt
- tracdap-runtime/python/setup.cfg
There is a regression for AWS S3 stroage in Apache Arrow 14:
https://github.com/apache/arrow/issues/38618
We need to hold off upgrading until this is addressed, or implement a workaround.
This change also rolls back support for Python 3.12. Arrow 14 comes with a wheel for 3.12 where Arrow 13 needs to run build wheel tools (these will fail on many machines that don't have all the extra build tools available).
> Revert Arrow 14 Upgrade

- gradle/versions.gradle
- tracdap-runtime/python/requirements.txt
- tracdap-runtime/python/setup.cfg
Upgrade to Arrow 14 is now possible with 14.0.2, following a regression fix for delete_dir() in Arrow's S3 filesystem
https://github.com/apache/arrow/issues/38618
> Feature/ Upgrade to Arrow 14

- .github/workflows/integration-cloud.yaml
- .github/workflows/integration.yml
- tracdap-runtime/python/README.md
- tracdap-runtime/python/requirements_plugins.txt
* GCP does not yet support Python 3.12: https://github.com/googleapis/python-crc32c/issues/178
* Azure does not yet support Python 3.12: https://github.com/aio-libs/multidict/issues/887
This is now noted in the Python docs. Integration for both GCP and Azure will run using Python 3.11 until supported upstream packages for Python 3.12 are released.
> Fix / Cloud dependencies for Python 3.12

- tracdap-plugins/gcp-storage/src/main/java/org/finos/tracdap/plugins/gcp/storage/GcsObjectStorage.java
Project shoudl no longer be specified in the full bucket name string on GCP
> Fix / GCP bucket naming convention

- dev/codegen/protoc-ctrl.py
- tracdap-libs/tracdap-lib-common/build.gradle
- tracdap-runtime/python/requirements.txt
- tracdap-runtime/python/setup.cfg
* Fix logging facade in the Java platform
* Fix code generation due to breaking changes in Protobuf
* Explicitly exclude support for NumPy 2, which has been released but is not binary compatible with NumPy 1
> Maintenance update

- tracdap-libs/tracdap-lib-data/src/test/java/org/finos/tracdap/common/storage/StorageOperationsTestSuite.java
- tracdap-libs/tracdap-lib-data/src/test/java/org/finos/tracdap/common/storage/StorageReadWriteTestSuite.java
- tracdap-runtime/python/test/tracdap_test/rt/suites/file_storage_suite.py
Test cases added to the Java storage test suite
No functional change as long paths on Windows are already working in Java
> Fix / Handle long paths on Windows (Java)

- tracdap-runtime/python/src/tracdap/rt/_impl/models.py
- tracdap-runtime/python/src/tracdap/rt/_impl/util.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/_helpers.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/repo_git.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_models.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_repos.py
Backport to address the most common problems with Windows max path length
Covers the model loader using Git repositories
The fix for local storage is not backported due to substantial updates in the storage layer for the 0.6 series
Storage managed by TRAC will not normally have issues with deeply nested paths
> Fix / Backport of Windows long path fix for model loading

- gradle/base-java.gradle
- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/model.proto
- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/object.proto
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/CommonValidators.java
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/FlowValidator.java
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/ModelValidator.java
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/static_/ObjectValidator.java
- tracdap-libs/tracdap-lib-validation/src/test/java/org/finos/tracdap/common/validation/static_/FlowValidatorTest.java
- tracdap-runtime/python/src/tracdap/rt/_impl/models.py
- tracdap-runtime/python/src/tracdap/rt/_impl/static_api.py
- tracdap-runtime/python/src/tracdap/rt/_impl/type_system.py
- tracdap-runtime/python/src/tracdap/rt/_impl/validation.py
- tracdap-runtime/python/src/tracdap/rt/api/hook.py
- tracdap-runtime/python/src/tracdap/rt/api/static_api.py
Props are not used by the TRAC engine but can be defined by applications to control application logic or store extra relevant information in the TRAC metadata model
> Feature / Allow setting props in the metadata model

- tracdap-runtime/python/src/tracdap/rt/_exec/dev_mode.py
- tracdap-runtime/python/src/tracdap/rt/_exec/runtime.py
- tracdap-runtime/python/src/tracdap/rt/_impl/config_parser.py
- tracdap-runtime/python/src/tracdap/rt/_plugins/config_local.py
- tracdap-runtime/python/src/tracdap/rt/ext/config.py
- tracdap-runtime/python/src/tracdap/rt/ext/plugins.py
- tracdap-runtime/python/src/tracdap/rt/launch/cli.py
- tracdap-runtime/python/src/tracdap/rt/launch/launch.py
- tracdap-runtime/python/test/tracdap_test/rt/api/test_model_api.py
- tracdap-runtime/python/test/tracdap_test/rt/exec/test_context.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_config_parser.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_models.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/test_ext/__init__.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/test_ext/test_ext_config_loader.py
- tracdap-runtime/python/test/tracdap_test/rt/plugins/test_plugin_pacakge.py
Separate config loading from config parsing
Allow config loading to be handled by external plugins
Provide a mechanism to let the runtime load external plugin packages
> Feature / Runtime config plugin

- tracdap-runtime/python/src/tracdap/rt/_exec/context.py
- tracdap-runtime/python/src/tracdap/rt/_impl/data.py
- tracdap-runtime/python/src/tracdap/rt/_impl/static_api.py
- tracdap-runtime/python/src/tracdap/rt/_impl/util.py
- tracdap-runtime/python/src/tracdap/rt/_impl/validation.py
- tracdap-runtime/python/src/tracdap/rt/api/experimental.py
- tracdap-runtime/python/test/tracdap_test/rt/exec/test_context.py
- tracdap-runtime/python/test/tracdap_test/rt/impl/test_data.py
- tracdap-runtime/python/test/tracdap_test/rt/suites/file_storage_suite.py
Make DATA_API a generic type (e.g. pandas, polars etc.)
Encapsulate logic for each data API into a single converter class
Allow TRAC to run when some data modules are missing
Pandas is still a hard dependency for now, but it doesn't have to be, this could be changed in the next major release
> Feature/  Generic runtime data protocols

- .gitignore
- examples/models/python/config/job_group.yaml
- examples/models/python/src/tutorial/data_import.py
- examples/models/python/src/tutorial/job_group.py
- tracdap-api/tracdap-metadata/src/main/proto/tracdap/metadata/job.proto
- tracdap-runtime/python/src/tracdap/rt/_exec/dev_mode.py
- tracdap-runtime/python/src/tracdap/rt/_exec/engine.py
- tracdap-runtime/python/src/tracdap/rt/_exec/functions.py
- tracdap-runtime/python/src/tracdap/rt/_exec/graph.py
- tracdap-runtime/python/src/tracdap/rt/_exec/graph_builder.py
- tracdap-runtime/python/src/tracdap/rt/_exec/runtime.py
- tracdap-runtime/python/test/tracdap_examples/test_tutorial.py
- tracdap-runtime/python/test/tracdap_test/rt/jobs/test_core_jobs.py
* Adds the concept of a child job to the runtime execution engine
* Job groups added to the metadata model for defining child jobs
* Parallel and sequential job groups are supported
* Nested job groups are supported
* Works with dev mode translation
* Includes an example job sequence for import -> process -> export
* Only available in the runtime, platform support will come later
> Feature / Runtime child jobs, parallel and sequential job groups

- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/grpc/DelayedExecutionInterceptor.java
- tracdap-libs/tracdap-lib-common/src/main/java/org/finos/tracdap/common/grpc/GrpcServiceRegister.java
- tracdap-libs/tracdap-lib-validation/src/main/java/org/finos/tracdap/common/validation/GrpcRequestValidator.java
- tracdap-runtime/python/requirements_plugins.txt
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/TracDataService.java
- tracdap-services/tracdap-svc-data/src/main/java/org/finos/tracdap/svc/data/api/TracDataApi.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/TracMetadataService.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/MetadataApiImpl.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/TracMetadataApi.java
- tracdap-services/tracdap-svc-meta/src/main/java/org/finos/tracdap/svc/meta/api/TrustedMetadataApi.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/TracOrchestratorService.java
- tracdap-services/tracdap-svc-orch/src/main/java/org/finos/tracdap/svc/orch/api/TracOrchestratorApi.java
* gRPC listeners require delayed execution of startCall(), which must happen after onMessage()
* To allow streaming calls, handling of the request() and onMessage() events is corrected for delayed execution
* Validation comes after auth but before API call start is recorded in the interceptor chain
> Feature / Move validation into gRPC interceptors

- examples/models/python/src/tutorial/data_export.py
- examples/models/python/src/tutorial/data_import.py
- examples/models/python/src/tutorial/hello_world.py
- tracdap-runtime/python/src/tracdap/rt/_impl/exec/context.py
- tracdap-runtime/python/src/tracdap/rt/api/model_api.py
- tracdap-runtime/python/test/tracdap_test/rt/exec/test_context.py
Backwards compatibility is maintained, so both old style and new style will work.
ctx.log.info("New style logging, ctx.log is a property")
ctx.log().info("Old style logging, ctx.log() is a method call")
> Feature / Make ctx.log a property
